---
    name: "st2cd_post_to_slack"
    description: "Post results of st2cd workflows to slack"
    enabled: true
    trigger:
        type: "core.st2.generic.actiontrigger"
    criteria:
        trigger.action_name:
            pattern: "st2cd\\.(st2_upgrade|integration_tests)"
            type: "matchregex"
    action:
        ref: "slack.post_message"
        parameters:
            message: "{{trigger.action_name}} {{trigger.status}} on {{trigger.parameters.hostname}}"
